name: Make Snapshots

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - "rhoai-*"
  repository_dispatch:
    types: [trigger-snapshot]

jobs:
  make-snapshots:
    runs-on: ubuntu-latest
    environment: redhat-internal
    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v4
        with:
          repository: red-hat-data-services/rhods-devops-infra

      - name: Set Up Environment Variables
        run: |
          echo "TOOLS_DIR=${{ github.workspace }}/tools" >> $GITHUB_ENV
          echo "SOURCE_DIR=${{ github.workspace }}/source" >> $GITHUB_ENV

      - name: Retrieve Secrets
        env:
          QUAY_API_TOKEN: ${{ secrets.QUAY_API_TOKEN }}
          K8S_SA_TOKEN: ${{ secrets.K8S_SA_TOKEN }}
          SLACK_APP_TOKEN: ${{ secrets.SLACK_APP_TOKEN }}
          SLACK_CHANNEL: ${{ env.DEVOPS_POC_SLACK_CHANNEL }}
          KUBERNETES_SERVICE_HOST: ${{ env.KONFLUX_K8S_SERVER }}
          KUBERNETES_SERVICE_PORT_HTTPS: ${{ env.KONFLUX_K8S_PORT }}
        run: |
          echo "::add-mask::$QUAY_API_TOKEN"
          echo "::add-mask::$K8S_SA_TOKEN"
          echo "::add-mask::$SLACK_TOKEN"

      - name: Generate Snapshot
        run: |
          set -eo pipefail
          cd $TOOLS_DIR/snapshot-generator
          ls -l
          export SNAPSHOT_TARGET="${{ github.event.client_payload.snapshot_target }}"
          echo "Snapshot target: $SNAPSHOT_TARGET"
          source ./ubuntu-install.sh
          bash ./conforma-reporter.sh
